import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString, IsInt, IsDate, Max, Min } from 'class-validator';

export class CreateReviewDto {
  @ApiPropertyOptional({
    description: 'ID of the review (autogenerated)',
    example: 1,
  })
  @IsOptional()
  @IsInt()
  id?: number;

  @ApiPropertyOptional({
    description: 'Description of the review',
    type: String,
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ description: 'Name of the reviewer', type: String })
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional({ description: 'Title of the review', type: String })
  @IsOptional()
  @IsString()
  title?: string;

  @ApiPropertyOptional({ description: 'Rating out of 5', example: 5 })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(5)
  rating?: number;

  @ApiPropertyOptional({ description: 'Associated package ID', example: 7 })
  @IsOptional()
  @IsInt()
  packageId?: number;

  @ApiPropertyOptional({ description: 'Associated media ID', example: 8 })
  @IsOptional()
  @IsInt()
  mediaId?: number;

  @ApiPropertyOptional({
    description: 'Date of the review',
    example: new Date().toISOString(),
  })
  @IsOptional()
  @IsString()
  reviewDate?: Date;
}
